version: 0.2

env: 
  parameter-store: 
    PASSWORD: dockerPassword
    USERNAME: dockerUser
phases:
  install: 
    commands: 
      - apt-get update -y 
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y 
      - apt-get install -y openjdk-8-jdk 
      - apt-get install -y maven 
  post_build: 
    commands: 
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - mvn deploy -Dmaven.test.skip=true -Ddockerfile.username=$USERNAME  -Ddockerfile.password=$PASSWORD
      - echo '[{"name":"CaliberEureka","imageUri":"revaturesierra/caliber-eureka"}]' > image.json
artifacts:
  files: image.json

